#pragma once

enum class CustomCursorEnum
{
	DEFAULT = 0,
	HAND = 1,
	QUAD_ARROW = 2,
	ZOOM_IN = 3,
	ZOOM_OUT = 4,
	EYE = 5,
	CROSSHAIR = 6,
	CROSSHAIR_RECTANGLE = 7,
	CROSSHAIR_SQUARE = 8,
	CROSSHAIR_ELLIPSE = 9,
	CROSSHAIR_CIRCLE = 10,
	CROSSHAIR_TRIANGLE = 11,
	CROSSHAIR_RIGHT_TRIANGLE = 12,
	CROSSHAIR_FLOWER = 13,
	CROSSHAIR_VERTICAL_ARROW = 14,
	CROSSHAIR_HORIZONTAL_ARROW = 15,
};